TOP_CUSTOMERS_COUNT = "TOP_CUSTOMERS_COUNT"
ORDERS_CSV_STORAGE = "ORDERS_CSV_STORAGE"
BARCODES_CSV_STORAGE = "BARCODES_CSV_STORAGE"

settings = {
    TOP_CUSTOMERS_COUNT: 5,
    ORDERS_CSV_STORAGE: "storage/orders.csv",
    BARCODES_CSV_STORAGE: "storage/barcodes.csv",
}
