repos:
  - repo: 'https://github.com/python/black'
    rev: 21.9b0
    hooks:
      - id: black
        name: Uncompromising Code Formatter (black)
        args:
          - "-l 120"
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.8.2
    hooks:
      - id: flake8
        name: Style Guide Enforcement (flake8)
        exclude: ^(html)|(ansible)|(terraform_prerequisites)|(terraform)|(packer)
        args:
          - '--max-line-length=120'
          - '--extend-ignore=E203,F401,F403'
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v2.4.3
    hooks:
      - id: pyupgrade
        name: Upgrade syntax for newer versions of the language (pyupgrade)
        args:
          - '--py38-plus'
  - repo: 'https://github.com/asottile/reorder_python_imports'
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports
        name: 'Reorder Python imports (src, tests)'
        files: ^(?!examples/)
        args:
          - '--application-directories'
          - src
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.1.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(html)|(ansible)|(terraform_prerequisites)|(terraform)|(packer)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
